namespace GameSDK.Localization
{
    public static class LanguageProperties
    {
        public static readonly Language[] Languages = {
            new() { Code = "aa", Name = "Afar", NativeName = "Afaraf" },
            new() { Code = "ab", Name = "Abkhaz", NativeName = "Аҧсуа бызшәа" },
            new() { Code = "ae", Name = "Avestan", NativeName = "Avesta" },
            new() { Code = "af", Name = "Afrikaans", NativeName = "Afrikaans" },
            new() { Code = "ak", Name = "Akan", NativeName = "Akan" },
            new() { Code = "am", Name = "Amharic", NativeName = "አማርኛ" },
            new() { Code = "an", Name = "Aragonese", NativeName = "Aragonés" },
            new() { Code = "ar", Name = "Arabic", NativeName = "اللغة العربية" },
            new() { Code = "as", Name = "Assamese", NativeName = "অসমীয়া" },
            new() { Code = "av", Name = "Avaric", NativeName = "Авар мацӀ" },
            new() { Code = "ay", Name = "Aymara", NativeName = "Aymar aru" },
            new() { Code = "az", Name = "Azerbaijani", NativeName = "Azərbaycan dili" },
            new() { Code = "ba", Name = "Bashkir", NativeName = "Башҡорт теле" },
            new() { Code = "be", Name = "Belarusian", NativeName = "Беларуская мова" },
            new() { Code = "bg", Name = "Bulgarian", NativeName = "Български език" },
            new() { Code = "bh", Name = "Bihari", NativeName = "भोजपुरी" },
            new() { Code = "bi", Name = "Bislama", NativeName = "Bislama" },
            new() { Code = "bm", Name = "Bambara", NativeName = "Bamanankan" },
            new() { Code = "bn", Name = "Bengali", NativeName = "বাংলা" },
            new() { Code = "bo", Name = "Tibetan Standard", NativeName = "བོད་ཡིག" },
            new() { Code = "br", Name = "Breton", NativeName = "Brezhoneg" },
            new() { Code = "bs", Name = "Bosnian", NativeName = "Bosanski jezik" },
            new() { Code = "ca", Name = "Catalan", NativeName = "Català" },
            new() { Code = "ce", Name = "Chechen", NativeName = "Нохчийн мотт" },
            new() { Code = "ch", Name = "Chamorro", NativeName = "Chamoru" },
            new() { Code = "co", Name = "Corsican", NativeName = "Corsu" },
            new() { Code = "cr", Name = "Cree", NativeName = "ᓀᐦᐃᔭᐍᐏᐣ" },
            new() { Code = "cs", Name = "Czech", NativeName = "Čeština" },
            new() { Code = "cu", Name = "Old Church Slavonic", NativeName = "Ѩзыкъ словѣньскъ" },
            new() { Code = "cv", Name = "Chuvash", NativeName = "Чӑваш чӗлхи" },
            new() { Code = "cy", Name = "Welsh", NativeName = "Cymraeg" },
            new() { Code = "da", Name = "Danish", NativeName = "Dansk" },
            new() { Code = "de", Name = "German", NativeName = "Deutsch" },
            new() { Code = "dv", Name = "Divehi", NativeName = "Dhivehi" },
            new() { Code = "dz", Name = "Dzongkha", NativeName = "རྫོང་ཁ" },
            new() { Code = "ee", Name = "Ewe", NativeName = "Eʋegbe" },
            new() { Code = "el", Name = "Greek", NativeName = "Ελληνικά" },
            new() { Code = "en", Name = "English", NativeName = "English" },
            new() { Code = "eo", Name = "Esperanto", NativeName = "Esperanto" },
            new() { Code = "es", Name = "Spanish", NativeName = "Español" },
            new() { Code = "et", Name = "Estonian", NativeName = "Eesti" },
            new() { Code = "eu", Name = "Basque", NativeName = "Euskara" },
            new() { Code = "fa", Name = "Persian", NativeName = "فارسی" },
            new() { Code = "ff", Name = "Fula", NativeName = "Fulfulde" },
            new() { Code = "fi", Name = "Finnish", NativeName = "Suomi" },
            new() { Code = "fj", Name = "Fijian", NativeName = "Vakaviti" },
            new() { Code = "fo", Name = "Faroese", NativeName = "Føroyskt" },
            new() { Code = "fr", Name = "French", NativeName = "Français" },
            new() { Code = "fy", Name = "Western Frisian", NativeName = "Frysk" },
            new() { Code = "ga", Name = "Irish", NativeName = "Gaeilge" },
            new() { Code = "gd", Name = "Scottish Gaelic", NativeName = "Gàidhlig" },
            new() { Code = "gl", Name = "Galician", NativeName = "Galego" },
            new() { Code = "gn", Name = "Guaraní", NativeName = "Avañeẽ" },
            new() { Code = "gu", Name = "Gujarati", NativeName = "ગુજરાતી" },
            new() { Code = "gv", Name = "Manx", NativeName = "Gaelg" },
            new() { Code = "ha", Name = "Hausa", NativeName = "هَوُسَ" },
            new() { Code = "he", Name = "Hebrew", NativeName = "עברית" },
            new() { Code = "hi", Name = "Hindi", NativeName = "हिन्दी" },
            new() { Code = "ho", Name = "Hiri Motu", NativeName = "Hiri Motu" },
            new() { Code = "hr", Name = "Croatian", NativeName = "Hrvatski jezik" },
            new() { Code = "ht", Name = "Haitian", NativeName = "Kreyòl ayisyen" },
            new() { Code = "hu", Name = "Hungarian", NativeName = "Magyar" },
            new() { Code = "hy", Name = "Armenian", NativeName = "Հայերեն" },
            new() { Code = "hz", Name = "Herero", NativeName = "Otjiherero" },
            new() { Code = "ia", Name = "Interlingua", NativeName = "Interlingua" },
            new() { Code = "id", Name = "Indonesian", NativeName = "Indonesian" },
            new() { Code = "ie", Name = "Interlingue", NativeName = "Interlingue" },
            new() { Code = "ig", Name = "Igbo", NativeName = "Asụsụ Igbo" },
            new() { Code = "ii", Name = "Nuosu", NativeName = "ꆈꌠ꒿ Nuosuhxop" },
            new() { Code = "ik", Name = "Inupiaq", NativeName = "Iñupiaq" },
            new() { Code = "io", Name = "Ido", NativeName = "Ido" },
            new() { Code = "is", Name = "Icelandic", NativeName = "Íslenska" },
            new() { Code = "it", Name = "Italian", NativeName = "Italiano" },
            new() { Code = "iu", Name = "Inuktitut", NativeName = "ᐃᓄᒃᑎᑐᑦ" },
            new() { Code = "ja", Name = "Japanese", NativeName = "日本語" },
            new() { Code = "jv", Name = "Javanese", NativeName = "Basa Jawa" },
            new() { Code = "ka", Name = "Georgian", NativeName = "Ქართული" },
            new() { Code = "kg", Name = "Kongo", NativeName = "Kikongo" },
            new() { Code = "ki", Name = "Kikuyu", NativeName = "Gĩkũyũ" },
            new() { Code = "kj", Name = "Kwanyama", NativeName = "Kuanyama" },
            new() { Code = "kk", Name = "Kazakh", NativeName = "Қазақ тілі" },
            new() { Code = "kl", Name = "Kalaallisut", NativeName = "Kalaallisut" },
            new() { Code = "km", Name = "Khmer", NativeName = "ខេមរភាសា" },
            new() { Code = "kn", Name = "Kannada", NativeName = "ಕನ್ನಡ" },
            new() { Code = "ko", Name = "Korean", NativeName = "한국어" },
            new() { Code = "kr", Name = "Kanuri", NativeName = "Kanuri" },
            new() { Code = "ks", Name = "Kashmiri", NativeName = "कश्मीरी" },
            new() { Code = "ku", Name = "Kurdish", NativeName = "Kurdî" },
            new() { Code = "kv", Name = "Komi", NativeName = "Коми кыв" },
            new() { Code = "kw", Name = "Cornish", NativeName = "Kernewek" },
            new() { Code = "ky", Name = "Kyrgyz", NativeName = "Кыргызча" },
            new() { Code = "la", Name = "Latin", NativeName = "Latine" },
            new() { Code = "lb", Name = "Luxembourgish", NativeName = "Lëtzebuergesch" },
            new() { Code = "lg", Name = "Ganda", NativeName = "Luganda" },
            new() { Code = "li", Name = "Limburgish", NativeName = "Limburgs" },
            new() { Code = "ln", Name = "Lingala", NativeName = "Lingála" },
            new() { Code = "lo", Name = "Lao", NativeName = "ພາສາ" },
            new() { Code = "lt", Name = "Lithuanian", NativeName = "Lietuvių kalba" },
            new() { Code = "lu", Name = "Luba-Katanga", NativeName = "Tshiluba" },
            new() { Code = "lv", Name = "Latvian", NativeName = "Latviešu valoda" },
            new() { Code = "mg", Name = "Malagasy", NativeName = "Fiteny malagasy" },
            new() { Code = "mh", Name = "Marshallese", NativeName = "Kajin M̧ajeļ" },
            new() { Code = "mi", Name = "Māori", NativeName = "Te reo Māori" },
            new() { Code = "mk", Name = "Macedonian", NativeName = "Македонски јазик" },
            new() { Code = "ml", Name = "Malayalam", NativeName = "മലയാളം" },
            new() { Code = "mn", Name = "Mongolian", NativeName = "Монгол хэл" },
            new() { Code = "mr", Name = "Marathi", NativeName = "मराठी" },
            new() { Code = "ms", Name = "Malay", NativeName = "هاس ملايو‎" },
            new() { Code = "mt", Name = "Maltese", NativeName = "Malti" },
            new() { Code = "my", Name = "Burmese", NativeName = "ဗမာစာ" },
            new() { Code = "na", Name = "Nauru", NativeName = "Ekakairũ Naoero" },
            new() { Code = "nb", Name = "Norwegian Bokmål", NativeName = "Norsk bokmål" },
            new() { Code = "nd", Name = "Northern Ndebele", NativeName = "IsiNdebele" },
            new() { Code = "ne", Name = "Nepali", NativeName = "नेपाली" },
            new() { Code = "ng", Name = "Ndonga", NativeName = "Owambo" },
            new() { Code = "nl", Name = "Dutch", NativeName = "Nederlands" },
            new() { Code = "nn", Name = "Norwegian Nynorsk", NativeName = "Norsk nynorsk" },
            new() { Code = "no", Name = "Norwegian", NativeName = "Norsk" },
            new() { Code = "nr", Name = "Southern Ndebele", NativeName = "IsiNdebele" },
            new() { Code = "nv", Name = "Navajo", NativeName = "Diné bizaad" },
            new() { Code = "ny", Name = "Chichewa", NativeName = "ChiCheŵa" },
            new() { Code = "oc", Name = "Occitan", NativeName = "Occitan" },
            new() { Code = "oj", Name = "Ojibwe", NativeName = "ᐊᓂᔑᓈᐯᒧᐎᓐ" },
            new() { Code = "om", Name = "Oromo", NativeName = "Afaan Oromoo" },
            new() { Code = "or", Name = "Oriya", NativeName = "ଓଡ଼ିଆ" },
            new() { Code = "os", Name = "Ossetian", NativeName = "Ирон æвзаг" },
            new() { Code = "pa", Name = "Panjabi", NativeName = "ਪੰਜਾਬੀ" },
            new() { Code = "pi", Name = "Pāli", NativeName = "पाऴि" },
            new() { Code = "pl", Name = "Polish", NativeName = "Język polski" },
            new() { Code = "ps", Name = "Pashto", NativeName = "پښتو" },
            new() { Code = "pt", Name = "Portuguese", NativeName = "Português" },
            new() { Code = "qu", Name = "Quechua", NativeName = "Runa Simi" },
            new() { Code = "rm", Name = "Romansh", NativeName = "Rumantsch grischun" },
            new() { Code = "rn", Name = "Kirundi", NativeName = "Ikirundi" },
            new() { Code = "ro", Name = "Romanian", NativeName = "Română" },
            new() { Code = "ru", Name = "Russian", NativeName = "Русский" },
            new() { Code = "rw", Name = "Kinyarwanda", NativeName = "Ikinyarwanda" },
            new() { Code = "sa", Name = "Sanskrit", NativeName = "संस्कृतम्" },
            new() { Code = "sc", Name = "Sardinian", NativeName = "Sardu" },
            new() { Code = "sd", Name = "Sindhi", NativeName = "सिन्धी" },
            new() { Code = "se", Name = "Northern Sami", NativeName = "Davvisámegiella" },
            new() { Code = "sg", Name = "Sango", NativeName = "Yângâ tî sängö" },
            new() { Code = "si", Name = "Sinhala", NativeName = "සිංහල" },
            new() { Code = "sk", Name = "Slovak", NativeName = "Slovenčina" },
            new() { Code = "sl", Name = "Slovene", NativeName = "Slovenski jezik" },
            new() { Code = "sm", Name = "Samoan", NativeName = "Gagana faa Samoa" },
            new() { Code = "sn", Name = "Shona", NativeName = "ChiShona" },
            new() { Code = "so", Name = "Somali", NativeName = "Soomaaliga" },
            new() { Code = "sq", Name = "Albanian", NativeName = "Shqip" },
            new() { Code = "sr", Name = "Serbian", NativeName = "Српски језик" },
            new() { Code = "ss", Name = "Swati", NativeName = "SiSwati" },
            new() { Code = "st", Name = "Southern Sotho", NativeName = "Sesotho" },
            new() { Code = "su", Name = "Sundanese", NativeName = "Basa Sunda" },
            new() { Code = "sv", Name = "Swedish", NativeName = "Svenska" },
            new() { Code = "sw", Name = "Swahili", NativeName = "Kiswahili" },
            new() { Code = "ta", Name = "Tamil", NativeName = "தமிழ்" },
            new() { Code = "te", Name = "Telugu", NativeName = "తెలుగు" },
            new() { Code = "tg", Name = "Tajik", NativeName = "Тоҷикӣ" },
            new() { Code = "th", Name = "Thai", NativeName = "ไทย" },
            new() { Code = "ti", Name = "Tigrinya", NativeName = "ትግርኛ" },
            new() { Code = "tk", Name = "Turkmen", NativeName = "Türkmen" },
            new() { Code = "tl", Name = "Tagalog", NativeName = "Wikang Tagalog" },
            new() { Code = "tn", Name = "Tswana", NativeName = "Setswana" },
            new() { Code = "to", Name = "Tonga", NativeName = "Faka Tonga" },
            new() { Code = "tr", Name = "Turkish", NativeName = "Türkçe" },
            new() { Code = "ts", Name = "Tsonga", NativeName = "Xitsonga" },
            new() { Code = "tt", Name = "Tatar", NativeName = "Татар теле" },
            new() { Code = "tw", Name = "Twi", NativeName = "Twi" },
            new() { Code = "ty", Name = "Tahitian", NativeName = "Reo Tahiti" },
            new() { Code = "ug", Name = "Uyghur", NativeName = "ئۇيغۇرچە‎" },
            new() { Code = "uk", Name = "Ukrainian", NativeName = "Українська" },
            new() { Code = "ur", Name = "Urdu", NativeName = "اردو" },
            new() { Code = "uz", Name = "Uzbek", NativeName = "Ўзбек" },
            new() { Code = "ve", Name = "Venda", NativeName = "Tshivenḓa" },
            new() { Code = "vi", Name = "Vietnamese", NativeName = "Tiếng Việt" },
            new() { Code = "vo", Name = "Volapük", NativeName = "Volapük" },
            new() { Code = "wa", Name = "Walloon", NativeName = "Walon" },
            new() { Code = "wo", Name = "Wolof", NativeName = "Wollof" },
            new() { Code = "xh", Name = "Xhosa", NativeName = "IsiXhosa" },
            new() { Code = "yi", Name = "Yiddish", NativeName = "ייִדיש" },
            new() { Code = "yo", Name = "Yoruba", NativeName = "Yorùbá" },
            new() { Code = "za", Name = "Zhuang", NativeName = "Saɯ cueŋƅ" },
            new() { Code = "zh", Name = "Chinese", NativeName = "中文" },
            new() { Code = "zu", Name = "Zulu", NativeName = "IsiZulu" },
        };
    }
}